spring:
  application:
    name: ms-cliente
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
server:
  port: 8099

spring.datasource:
  url: jdbc:postgresql://localhost:5432/ms_cliente_db
  username: root
  password:   root_password
  driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10